name       : nfft
version    : 3.4.1
release    : 2
source     :
    - https://github.com/NFFT/nfft/archive/3.4.1.tar.gz : 4e05a7b74abf5073e0c9c54b4692961c43399479676587206cf67f713464f73c
license    : GPL-2.0
summary    : Nonequispaced Fourier transform library
description: |
    NFFT is a C subroutine library for computing the nonequispaced discrete Fourier transform (NDFT) in one or more dimensions, of arbitrary input size, and of complex data.
component  : programming.library
builddeps  :
    - pkgconfig(fftw3)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
