name       : nfft
version    : 3.4.0
release    : 1
source     :
    - https://www-user.tu-chemnitz.de/~potts/nfft/download/nfft-3.4.0.tar.gz : c62958548674be28b99331320430d5adddf3b1da8bd5e523edc7ec0aac4c9991
license    : GPL-2.0
summary    : Nonequispaced Fourier transform library
description: |
    NFFT is a C subroutine library for computing the nonequispaced discrete Fourier transform (NDFT) in one or more dimensions, of arbitrary input size, and of complex data.
component  : programming.library
builddeps  :
    - pkgconfig(fftw3)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
